// Generated by CoffeeScript 1.9.3
(function() {
  var Animation, EventEmitter, _,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _ = require('lodash');

  EventEmitter = require('../lib/event_emitter');

  module.exports = Animation = (function(superClass) {
    extend(Animation, superClass);

    function Animation(options) {
      Animation.__super__.constructor.apply(this, arguments);
      _.extend(this, options);
      this.engine || (this.engine = require('../engine'));
    }

    Animation.prototype.update = function() {};

    return Animation;

  })(EventEmitter);

}).call(this);
