// Generated by CoffeeScript 1.9.3
(function() {
  var Board, Entity,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Entity = require('./entity');

  module.exports = Board = (function(superClass) {
    extend(Board, superClass);

    Board.prototype._name = 'board';

    function Board() {
      Board.__super__.constructor.apply(this, arguments);
      this.addComponent('position');
      this.addComponent('hex_grid');
      this.addComponent('view');
      this.addComponent('relations');
      window.board = this;
    }

    return Board;

  })(Entity);

}).call(this);
