// Generated by CoffeeScript 1.7.1
(function() {
  var Board, Entity,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('./entity');

  module.exports = Board = (function(_super) {
    __extends(Board, _super);

    Board.prototype._name = 'Board';

    function Board() {
      this.init = __bind(this.init, this);
      Board.__super__.constructor.apply(this, arguments);
      this.addComponent('position');
      this.addComponent('hex_grid');
      this.addComponent('view', 'views/view');
      this.addComponent('relations');
      window.board = this;
    }

    Board.prototype.init = function() {
      return Board.__super__.init.apply(this, arguments);
    };

    Board.prototype.toString = function() {
      return ['Board: ', this.x, this.y];
    };

    return Board;

  })(Entity);

}).call(this);
