// Generated by CoffeeScript 1.7.1
(function() {
  var Entity, GridTile,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('./entity');

  module.exports = GridTile = (function(_super) {
    __extends(GridTile, _super);

    GridTile.prototype._name = 'GridTile';

    function GridTile() {
      this.toString = __bind(this.toString, this);
      GridTile.__super__.constructor.apply(this, arguments);
      this.text_anchor = {
        x: 0,
        y: 0
      };
      this.text_position = {
        x: 0,
        y: 0
      };
      this.text_format = {
        font: 'regular 8px Arial',
        fill: '#ffffff'
      };
      this.selected_texture = 'assets/tiles/tileWater_full.png';
      this.hover_texture = 'assets/tiles/tileMagic_full.png';
      this.addComponent('hex_position');
      this.addComponent('view', 'views/sprite', {
        texture: 'assets/tiles/tileGrass_full.png'
      });
      this.addComponent('sub_view', 'views/text');
      this.addComponent('position');
      this.addComponent('relations');
      this.addComponent('hover_effects', {
        outline: {
          colour: 0xffffff
        }
      });
      this.addComponent('highlight');
      this.addComponent('tile');
    }

    GridTile.prototype.toString = function() {
      var s;
      s = "q: " + this.q;
      s += "\nr: " + this.r;
      return s;
    };

    return GridTile;

  })(Entity);

}).call(this);
