// Generated by CoffeeScript 1.9.3
(function() {
  var Entity, GridTile,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Entity = require('./entity');

  module.exports = GridTile = (function(superClass) {
    extend(GridTile, superClass);

    GridTile.prototype._name = 'grid_tile';

    function GridTile() {
      this.toString = bind(this.toString, this);
      GridTile.__super__.constructor.apply(this, arguments);
      this.selected_texture = 'assets/tiles/tileWater_full.png';
      this.hover_texture = 'assets/tiles/tileMagic_full.png';
      this.addComponent('hex_position');
      this.addComponent('view', 'sprite', {
        texture: 'assets/tiles/tileGrass.png'
      });
      this.addComponent('sub_view', 'text', {
        text_position: {
          x: 40,
          y: 20
        }
      });
      this.addComponent('position');
      this.addComponent('relations');
      this.addComponent('hover_effects');
      this.addComponent('highlight', {
        texture: this.hover_texture
      });
      this.addComponent('tile');
    }

    GridTile.prototype.toString = function() {
      return this.hex_position.q + " " + this.hex_position.r;
    };

    return GridTile;

  })(Entity);

}).call(this);
