// Generated by CoffeeScript 1.7.1
(function() {
  var Entity, Player,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('./entity');

  module.exports = Player = (function(_super) {
    __extends(Player, _super);

    Player.prototype._name = 'Player';

    function Player() {
      this.toString = __bind(this.toString, this);
      var _base;
      Player.__super__.constructor.apply(this, arguments);
      (_base = this.options).view || (_base.view = {
        texture: 'assets/tiles/alienGreen.png'
      });
      this.addComponent('hex_position');
      this.addComponent('view', 'views/sprite');
      this.addComponent('sub_view', 'views/text');
      this.addComponent('position');
      this.addComponent('relations');
      this.addComponent('hover_effects', {
        outline: {
          colour: 0xdddd77
        }
      });
      this.addComponent('selectable');
      this.addComponent('pathable');
      this.addComponent('player');
    }

    Player.prototype.toString = function() {
      return this.name;
    };

    return Player;

  })(Entity);

}).call(this);
