// Generated by CoffeeScript 1.7.1
(function() {
  var Entity, Team,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('./entity');

  module.exports = Team = (function(_super) {
    __extends(Team, _super);

    function Team(attrs) {
      this.toString = __bind(this.toString, this);
      Team.__super__.constructor.apply(this, arguments);
      this.addComponent('team');
    }

    Team.prototype.toString = function() {
      var s;
      s = "q: " + this.q;
      s += "\nr: " + this.r;
      return s;
    };

    return Team;

  })(Entity);

}).call(this);
