// Generated by CoffeeScript 1.9.3
(function() {
  var Entity, Unit,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Entity = require('./entity');

  module.exports = Unit = (function(superClass) {
    extend(Unit, superClass);

    Unit.prototype._name = 'unit';

    function Unit() {
      var base;
      Unit.__super__.constructor.apply(this, arguments);
      (base = this.options).view || (base.view = {
        texture: 'assets/tiles/alienGreen.png'
      });
      this.addComponent('hex_position');
      this.addComponent('view', 'sprite');
      this.addComponent('sub_view', 'text');
      this.addComponent('position');
      this.addComponent('relations');
      this.addComponent('hover_effects', {
        outline: {
          colour: 0xdddd77
        }
      });
      this.addComponent('selectable');
      this.addComponent('pathable');
      this.addComponent('team_membership');
      this.addComponent('animations');
    }

    return Unit;

  })(Entity);

}).call(this);
