// Generated by CoffeeScript 1.7.1
(function() {
  var Engine, MultiplayerSystem, System, cloak,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Engine = require('../engine/engine');

  System = require('./system');

  cloak = require('cloak');

  module.exports = MultiplayerSystem = (function(_super) {
    __extends(MultiplayerSystem, _super);

    function MultiplayerSystem() {
      this.sendCommand = __bind(this.sendCommand, this);
      this.onCommand = __bind(this.onCommand, this);
      this.init = __bind(this.init, this);
      return MultiplayerSystem.__super__.constructor.apply(this, arguments);
    }

    MultiplayerSystem.prototype._name = 'multiplayer';

    MultiplayerSystem.prototype.init = function() {
      MultiplayerSystem.__super__.init.apply(this, arguments);
      this.primus = new Primus(this.url);
      this.socket = this.primus.channel('clients');
      this.socket.on('command', this.onCommand);
      return this.id = this.socket.id;
    };

    MultiplayerSystem.prototype.onCommand = function(data) {
      var Command, command;
      console.log('id', this.socket.id);
      console.log('server said: ' + data);
      if (data.user_id === this.id) {
        return;
      }
      if (!(Command = Engine.getCommand(data.command))) {
        console.error('Command not found: ', data.command);
      }
      command = new Command(data.data, {
        remote: true
      });
      return Engine.getSystem('command_queue').push(command);
    };

    MultiplayerSystem.prototype.sendCommand = function(command) {
      return this.socket.send('command', command.toJSON());
    };

    return MultiplayerSystem;

  })(System);

}).call(this);
