// Generated by CoffeeScript 1.9.3
(function() {
  var State;

  module.exports = State = (function() {
    function State() {}

    State.prototype.init = function() {};

    State.prototype.preload = function() {};

    State.prototype.create = function() {};

    State.prototype.update = function() {};

    State.prototype.paused = function() {};

    State.prototype.shutdown = function() {};

    return State;

  })();

}).call(this);
