// Generated by CoffeeScript 1.7.1
(function() {
  var Action, _;

  _ = require('underscore');

  module.exports = Action = (function() {
    function Action(options) {
      _.extend(this, options);
    }

    Action.prototype.update = function() {};

    return Action;

  })();

}).call(this);
