// Generated by CoffeeScript 1.7.1
(function() {
  var Circle, Component, PIXI,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./../component');

  PIXI = require('pixi');

  module.exports = Circle = (function(_super) {
    __extends(Circle, _super);

    function Circle() {
      this.createDisplayObject = __bind(this.createDisplayObject, this);
      return Circle.__super__.constructor.apply(this, arguments);
    }

    Circle.prototype._name = 'circle';

    Circle.prototype.createDisplayObject = function() {
      this.display_object = new PIXI.Graphics();
      this.display_object.beginFill(0xFFFF00);
      this.display_object.lineStyle(5, 0xFF0000);
      this.display_object.drawCircle(100, 100, 5);
      return this.display_object;
    };

    return Circle;

  })(Component);

}).call(this);
