// Generated by CoffeeScript 1.9.3
(function() {
  var Circle, Component, PIXI,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./../component');

  PIXI = require('pixi.js');

  module.exports = Circle = (function(superClass) {
    extend(Circle, superClass);

    function Circle() {
      this.createDisplayObject = bind(this.createDisplayObject, this);
      return Circle.__super__.constructor.apply(this, arguments);
    }

    Circle.prototype._name = 'circle';

    Circle.prototype.createDisplayObject = function() {
      this.display_object = new PIXI.Graphics();
      this.display_object.beginFill(0xFFFF00);
      this.display_object.lineStyle(5, 0xFF0000);
      this.display_object.drawCircle(100, 100, 5);
      this.entity.emit('view/display_object_created');
      return this.display_object;
    };

    return Circle;

  })(Component);

}).call(this);
