// Generated by CoffeeScript 1.7.1
(function() {
  var PIXI, Sprite, View,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('./view');

  PIXI = require('pixi');

  module.exports = Sprite = (function(_super) {
    __extends(Sprite, _super);

    function Sprite() {
      this.createDisplayObject = __bind(this.createDisplayObject, this);
      return Sprite.__super__.constructor.apply(this, arguments);
    }

    Sprite.prototype._name = 'sprite';

    Sprite.prototype.createDisplayObject = function() {
      if (!this.texture) {
        return new Error('Sprite missing texture');
      }
      this.pixi_texture = PIXI.Texture.fromImage(this.texture);
      this.display_object = new PIXI.Sprite(this.pixi_texture);
      return this.display_object;
    };

    return Sprite;

  })(View);

}).call(this);
