// Generated by CoffeeScript 1.7.1
(function() {
  var Component, View,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('../component');

  module.exports = View = (function(_super) {
    __extends(View, _super);

    function View() {
      return View.__super__.constructor.apply(this, arguments);
    }

    View.prototype._name = 'view';

    View.prototype.createDisplayObject = function() {
      this.display_object = new PIXI.DisplayObjectContainer();
      return this.display_object;
    };

    return View;

  })(Component);

}).call(this);
