// Generated by CoffeeScript 1.7.1
(function() {
  var Animations, Component,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Animations = (function(_super) {
    __extends(Animations, _super);

    Animations.prototype._name = 'animations';

    function Animations() {
      Animations.__super__.constructor.apply(this, arguments);
      this.tweens || (this.tweens = {});
    }

    return Animations;

  })(Component);

}).call(this);
