// Generated by CoffeeScript 1.7.1
(function() {
  var Clickable, Component,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Clickable = (function(_super) {
    __extends(Clickable, _super);

    function Clickable() {
      this.onClick = __bind(this.onClick, this);
      this.init = __bind(this.init, this);
      return Clickable.__super__.constructor.apply(this, arguments);
    }

    Clickable.prototype._name = 'clickable';

    Clickable.prototype.init = function() {
      this.selected = false;
      this.entity.display_object.setInteractive(true);
      return this.entity.display_object.click = this.onClick;
    };

    Clickable.prototype.onClick = function(event) {
      return this.entity.emit('click', event);
    };

    return Clickable;

  })(Component);

}).call(this);
