// Generated by CoffeeScript 1.9.3
(function() {
  var Component, _,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('lodash');

  module.exports = Component = (function() {
    function Component(entity, options) {
      this.entity = entity;
      this.destroy = bind(this.destroy, this);
      this.requires = bind(this.requires, this);
      _.extend(this, options);
      this.engine || (this.engine = require('../engine'));
    }

    Component.prototype.requires = function(components) {
      var component, i, len, results;
      if (!_.isArray(components)) {
        components = [components];
      }
      results = [];
      for (i = 0, len = components.length; i < len; i++) {
        component = components[i];
        if (!this.entity.hasComponent(component)) {
          throw new Error("Missing component " + component + " from entity: " + this.entity._name);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    Component.prototype.destroy = function() {};

    return Component;

  })();

}).call(this);
