// Generated by CoffeeScript 1.7.1
(function() {
  var Component, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  module.exports = Component = (function() {
    function Component(entity, options) {
      this.entity = entity;
      this.requires = __bind(this.requires, this);
      _.extend(this, options);
    }

    Component.prototype.requires = function(components) {
      var component, _i, _len, _results;
      if (!_.isArray(components)) {
        components = [components];
      }
      _results = [];
      for (_i = 0, _len = components.length; _i < _len; _i++) {
        component = components[_i];
        if (!this.entity.hasComponent(component)) {
          throw new Error("Missing component " + component + " from entity: " + this.entity._name);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Component;

  })();

}).call(this);
