// Generated by CoffeeScript 1.7.1
(function() {
  var Component, HexPosition, HexUtils,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  HexUtils = require('../lib/hex_utils');

  module.exports = HexPosition = (function(_super) {
    __extends(HexPosition, _super);

    function HexPosition() {
      this.toCubeCoords = __bind(this.toCubeCoords, this);
      this.setHexPosition = __bind(this.setHexPosition, this);
      return HexPosition.__super__.constructor.apply(this, arguments);
    }

    HexPosition.prototype._name = 'hex_position';

    HexPosition.prototype.setHexPosition = function(q, r) {
      this.q = q;
      return this.r = r;
    };

    HexPosition.prototype.toCubeCoords = function() {
      return HexUtils.axialToCoubeCoords(this.q, this.r);
    };

    return HexPosition;

  })(Component);

}).call(this);
