// Generated by CoffeeScript 1.9.3
(function() {
  var Component, HexGrid,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = HexGrid = (function(superClass) {
    extend(HexGrid, superClass);

    function HexGrid() {
      return HexGrid.__super__.constructor.apply(this, arguments);
    }

    HexGrid.prototype._name = 'hex_grid';

    return HexGrid;

  })(Component);

}).call(this);
