// Generated by CoffeeScript 1.7.1
(function() {
  var Component, HexGrid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = HexGrid = (function(_super) {
    __extends(HexGrid, _super);

    function HexGrid() {
      return HexGrid.__super__.constructor.apply(this, arguments);
    }

    HexGrid.prototype._name = 'hex_grid';

    return HexGrid;

  })(Component);

}).call(this);
