// Generated by CoffeeScript 1.9.3
(function() {
  var Component, Highlight,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = Highlight = (function(superClass) {
    extend(Highlight, superClass);

    function Highlight() {
      return Highlight.__super__.constructor.apply(this, arguments);
    }

    Highlight.prototype._name = 'highlight';

    return Highlight;

  })(Component);

}).call(this);
