// Generated by CoffeeScript 1.7.1
(function() {
  var Component, Highlight,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Highlight = (function(_super) {
    __extends(Highlight, _super);

    function Highlight() {
      return Highlight.__super__.constructor.apply(this, arguments);
    }

    Highlight.prototype._name = 'highlight';

    return Highlight;

  })(Component);

}).call(this);
