// Generated by CoffeeScript 1.9.3
(function() {
  var Component, HoverEffects,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = HoverEffects = (function(superClass) {
    extend(HoverEffects, superClass);

    function HoverEffects() {
      return HoverEffects.__super__.constructor.apply(this, arguments);
    }

    HoverEffects.prototype._name = 'hover_effects';

    return HoverEffects;

  })(Component);

}).call(this);
