// Generated by CoffeeScript 1.7.1
(function() {
  var Component, Pathable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Pathable = (function(_super) {
    __extends(Pathable, _super);

    function Pathable() {
      return Pathable.__super__.constructor.apply(this, arguments);
    }

    Pathable.prototype._name = 'pathable';

    return Pathable;

  })(Component);

}).call(this);
