// Generated by CoffeeScript 1.9.3
(function() {
  var Component, Pathable,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = Pathable = (function(superClass) {
    extend(Pathable, superClass);

    function Pathable() {
      return Pathable.__super__.constructor.apply(this, arguments);
    }

    Pathable.prototype._name = 'pathable';

    return Pathable;

  })(Component);

}).call(this);
