// Generated by CoffeeScript 1.7.1
(function() {
  var Component, Position,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Position = (function(_super) {
    __extends(Position, _super);

    function Position() {
      return Position.__super__.constructor.apply(this, arguments);
    }

    Position.prototype._name = 'position';

    return Position;

  })(Component);

}).call(this);
