// Generated by CoffeeScript 1.9.3
(function() {
  var Component, Selectable,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = Selectable = (function(superClass) {
    extend(Selectable, superClass);

    function Selectable() {
      return Selectable.__super__.constructor.apply(this, arguments);
    }

    Selectable.prototype._name = 'selectable';

    return Selectable;

  })(Component);

}).call(this);
