// Generated by CoffeeScript 1.7.1
(function() {
  var Component, Selectable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Selectable = (function(_super) {
    __extends(Selectable, _super);

    function Selectable() {
      return Selectable.__super__.constructor.apply(this, arguments);
    }

    Selectable.prototype._name = 'selectable';

    return Selectable;

  })(Component);

}).call(this);
