// Generated by CoffeeScript 1.9.3
(function() {
  var Component, Team,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = Team = (function(superClass) {
    extend(Team, superClass);

    Team.prototype._name = 'team';

    function Team(entity, options) {
      this.entity = entity;
      Team.__super__.constructor.apply(this, arguments);
      this.units || (this.units = []);
    }

    return Team;

  })(Component);

}).call(this);
