// Generated by CoffeeScript 1.7.1
(function() {
  var Component, Team,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Component = require('./component');

  module.exports = Team = (function(_super) {
    __extends(Team, _super);

    Team.prototype._name = 'team';

    function Team(entity, options) {
      this.entity = entity;
      Team.__super__.constructor.apply(this, arguments);
      this.players || (this.players = []);
    }

    return Team;

  })(Component);

}).call(this);
