// Generated by CoffeeScript 1.9.3
(function() {
  var Component, Tile,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Component = require('./component');

  module.exports = Tile = (function(superClass) {
    extend(Tile, superClass);

    function Tile() {
      return Tile.__super__.constructor.apply(this, arguments);
    }

    Tile.prototype._name = 'tile';

    return Tile;

  })(Component);

}).call(this);
