// Generated by CoffeeScript 1.7.1
(function() {
  var Context, Engine, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  Engine = require('../engine/engine');

  module.exports = Context = (function() {
    function Context(options) {
      this.onEntityClick = __bind(this.onEntityClick, this);
      this.bindEvents = __bind(this.bindEvents, this);
      this.addSubContext = __bind(this.addSubContext, this);
      this.onEntityDestroyed = __bind(this.onEntityDestroyed, this);
      this.onEntityCreated = __bind(this.onEntityCreated, this);
      _.extend(this, options);
      this.entities = [];
      this.sub_contexts = [];
      Engine.on('entity/created', this.onEntityCreated);
      Engine.on('entity/destroyed', this.onEntityDestroyed);
    }

    Context.prototype.onEntityCreated = function(entity) {};

    Context.prototype.onEntityDestroyed = function(entity) {};

    Context.prototype.addSubContext = function(context) {
      var Ctx;
      Ctx = require("./" + context);
      return this.sub_contexts.push(new Ctx);
    };

    Context.prototype.bindEvents = function() {
      var entity, _i, _len, _ref, _results;
      _ref = Engine.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        _results.push(entity.on('click', this.onEntityClick));
      }
      return _results;
    };

    Context.prototype.onEntityClick = function() {
      if (!this.active) {

      }
    };

    return Context;

  })();

}).call(this);
