// Generated by CoffeeScript 1.7.1
(function() {
  var Engine, SelectAllyMixin, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  Engine = require('../../engine/engine');

  module.exports = SelectAllyMixin = (function() {
    function SelectAllyMixin() {
      this.select = __bind(this.select, this);
    }

    SelectAllyMixin.prototype.activate = function() {
      var entity, _i, _len, _ref, _results;
      this.targets = Engine.entitiesByComponent('selectable');
      _ref = this.targets;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        _results.push(entity.on('click', this.select));
      }
      return _results;
    };

    SelectAllyMixin.prototype.deactivate = function() {
      var entity, _i, _len, _ref, _results;
      _ref = this.targets;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        _results.push(entity.off('click', this.select));
      }
      return _results;
    };

    SelectAllyMixin.prototype.select = function(e, entity) {
      return Engine.getSystem('selectables').select(entity);
    };

    return SelectAllyMixin;

  })();

}).call(this);
