// Generated by CoffeeScript 1.9.3
(function() {
  var AnimationUtils, HIT_THRESHOLD, MIN_SPEED, _, tweene;

  _ = require('lodash');

  tweene = require('tween.js');

  MIN_SPEED = 0.5;

  HIT_THRESHOLD = 1;

  module.exports = AnimationUtils = (function() {
    function AnimationUtils() {}

    AnimationUtils.reachedTarget = function(entity, target) {
      return Math.abs(entity.position.x - target.position.x) < HIT_THRESHOLD && Math.abs(entity.position.y - target.position.y) < HIT_THRESHOLD;
    };

    AnimationUtils.updatePosition = function(entity, target, speed) {
      var dx, dy;
      dx = (target.position.x - entity.position.x) * speed;
      dy = (target.position.y - entity.position.y) * speed;
      if (dx > 0 && dx < MIN_SPEED) {
        dx = MIN_SPEED;
      }
      if (dx < 0 && dx > -MIN_SPEED) {
        dx = -MIN_SPEED;
      }
      if (dy > 0 && dy < MIN_SPEED) {
        dy = MIN_SPEED;
      }
      if (dy < 0 && dy > -MIN_SPEED) {
        dy = -MIN_SPEED;
      }
      entity.position.x += dx;
      return entity.position.y += dy;
    };

    AnimationUtils.toTarget = function(engine, hex_position) {
      var pixel_coords;
      if (hex_position.position) {
        return hex_position;
      }
      pixel_coords = engine.getSystem('hex_grid').coordsToPixel(hex_position);
      return {
        position: pixel_coords,
        hex_position: hex_position
      };
    };

    return AnimationUtils;

  })();

}).call(this);
