// Generated by CoffeeScript 1.9.3
(function() {
  var DEFAULTS, EffectUtils, PIXI;

  PIXI = require('pixi.js');

  DEFAULTS = {
    OUTLINE_COLOUR: '#ffff55'
  };

  module.exports = EffectUtils = (function() {
    function EffectUtils() {}

    EffectUtils.initEffects = function(entity, component) {
      if (component.outline) {
        EffectUtils.createOutline(entity, component);
      }
      return entity;
    };

    EffectUtils.createOutline = function(entity, component) {
      component.display_object = new PIXI.Graphics();
      component.display_object.lineStyle(1, component.outline.colour || DEFAULTS.OUTLINE_COLOUR);
      component.display_object.drawCircle(0, 0, 35);
      component.display_object.endFill();
      component.display_object.position.x = 35;
      return component.display_object.position.y = 35;
    };

    EffectUtils.activate = function(entity, component) {
      if (component.outline) {
        return entity.view.display_object.addChild(component.display_object);
      } else if (component.texture) {
        component.previous_texture = entity.view.display_object.texture;
        return entity.view.display_object.texture = PIXI.Texture.fromImage(component.texture);
      }
    };

    EffectUtils.deactivate = function(entity, component) {
      if (component.outline) {
        return entity.view.display_object.removeChild(component.display_object);
      } else if (component.texture) {
        return entity.view.display_object.texture = component.previous_texture;
      }
    };

    return EffectUtils;

  })();

}).call(this);
