// Generated by CoffeeScript 1.7.1
(function() {
  var HexUtils;

  module.exports = HexUtils = (function() {
    function HexUtils() {}

    HexUtils.NEIGHBOURS = [[+1, 0], [+1, -1], [0, -1], [-1, 0], [-1, +1], [0, +1]];

    HexUtils.heightFromSize = function(size) {
      return size * 2;
    };

    HexUtils.widthFromSize = function(size) {
      return Math.sqrt(3) / 2 * HexUtils.heightFromSize(size);
    };

    HexUtils.neighbour = function(q, r, direction) {
      var d, _ref;
      if (arguments.length === 2) {
        direction = r;
        _ref = q, q = _ref.q, r = _ref.r;
      }
      d = HexUtils.NEIGHBOURS[direction];
      return {
        q: q + d[0],
        r: r + d[1]
      };
    };

    HexUtils.axialToCubeCoords = function(q, r) {
      return {
        x: q,
        z: r,
        y: -q - r
      };
    };

    HexUtils.cubeToAxialCoords = function(x, y, z) {
      return {
        q: x,
        r: z
      };
    };

    HexUtils.pixelToCoords = function(x, y, tile_size) {
      var q, r;
      q = (1 / 3 * Math.sqrt(3) * x - 1 / 3 * y) / tile_size;
      r = 2 / 3 * y / tile_size;
      return HexUtils.roundCoords(q, r);
    };

    HexUtils.roundCoords = function(q, r) {
      var x, y, z, _ref, _ref1;
      if (arguments.length === 1) {
        _ref = q, q = _ref.q, r = _ref.r;
      }
      _ref1 = HexUtils.roundCoordsCubic(HexUtils.axialToCubeCoords(q, r)), x = _ref1.x, y = _ref1.y, z = _ref1.z;
      return HexUtils.cubeToAxialCoords(x, y, z);
    };

    HexUtils.roundCoordsCubic = function(x, y, z) {
      var rx, ry, rz, x_diff, y_diff, z_diff, _ref;
      if (arguments.length === 1) {
        _ref = x, x = _ref.x, y = _ref.y, z = _ref.z;
      }
      rx = Math.round(x);
      ry = Math.round(y);
      rz = Math.round(z);
      x_diff = Math.abs(rx - x);
      y_diff = Math.abs(ry - y);
      z_diff = Math.abs(rz - z);
      if (x_diff > y_diff && x_diff > z_diff) {
        rx = -ry - rz;
      } else if (y_diff > z_diff) {
        ry = -rx - rz;
      } else {
        rz = -rx - ry;
      }
      return {
        x: rx,
        y: ry,
        z: rz
      };
    };

    HexUtils.distance = function(r1, q1, r2, q2) {
      var _ref, _ref1;
      if (arguments.length === 2) {
        _ref = [q1.q, q1.r], q2 = _ref[0], r2 = _ref[1];
        _ref1 = [r1.q, r1.r], q1 = _ref1[0], r1 = _ref1[1];
      }
      return HexUtils.distanceCubic(HexUtils.axialToCubeCoords(q1, r1), HexUtils.axialToCubeCoords(q2, r2));
    };

    HexUtils.distanceCubic = function(x1, y1, z1, x2, y2, z2) {
      var _ref, _ref1;
      if (arguments.length === 2) {
        _ref = [y1.x, y1.y, y1.z], x2 = _ref[0], y2 = _ref[1], z2 = _ref[2];
        _ref1 = [x1.x, x1.y, x1.z], x1 = _ref1[0], y1 = _ref1[1], z1 = _ref1[2];
      }
      return Math.max(Math.abs(x1 - x2), Math.abs(y1 - y2), Math.abs(z1 - z2));
    };

    HexUtils.line = function(r1, q1, r2, q2) {
      var da, db, i, n, points, _i, _ref, _ref1;
      if (arguments.length === 2) {
        _ref = [q1.q, q1.r], q2 = _ref[0], r2 = _ref[1];
        _ref1 = [r1.q, r1.r], q1 = _ref1[0], r1 = _ref1[1];
      }
      points = [];
      n = HexUtils.distance(r1, q1, r2, q2);
      for (i = _i = 0; 0 <= n ? _i <= n : _i >= n; i = 0 <= n ? ++_i : --_i) {
        db = i / n;
        da = 1 - db;
        points.push(HexUtils.roundCoords(q1 * da + q2 * db, r1 * da + r2 * db));
      }
      return points;
    };

    return HexUtils;

  })();

}).call(this);
