// Generated by CoffeeScript 1.7.1
(function() {
  var Command, Engine, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _ = require('underscore');

  Engine = require('../engine/engine');

  module.exports = Command = (function() {
    function Command(data, options) {
      this.data = data;
      this.options = options != null ? options : {};
      this.toJSON = __bind(this.toJSON, this);
      this.set = __bind(this.set, this);
      this.set(this.data);
    }

    Command.prototype.set = function(data) {
      if (data.entity) {
        data.entity = Engine.ensureEntity(data.entity);
      }
      if (data.target) {
        data.target = Engine.ensureEntity(data.target);
      }
      console.log('after', data);
      return _.extend(this, data);
    };

    Command.prototype.toJSON = function() {
      return {
        command: this._name,
        data: this.data
      };
    };

    return Command;

  })();

}).call(this);
